rpc:
  name: xixi-rpc
  version: 2.0
  serverHost: localhost
  serverPort: 8081
  serializer: json
  retryStrategy: fixedInterval
  tolerantStrategy: failOver
  loadBalancer: consistentHash
  register:
    registry: etcd
    address: http://localhost:2379
    timeout: 30
  #mock: true