rpc:
  name: xixi-rpc
  version: 2.0
  serverHost: localhost
  serverPort: 8080
  serializer: json
  #大写开头
  loadBalancer: ConsistentHash
  register:
    registry: etcd
    address: http://localhost:2379
    timeout: 30
  #mock: true